services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  
  toxiproxy:
    build: .
    container_name: mysql-delay-proxy
    ports:
      - "3307:3307"  # app connects to 3307 for delayed db
      - "8474:8474" # admin port
    depends_on:
      - mysql
